#!/usr/bin/env bash
set -e
[ -n "$GRNENV_DEBUG" ] && set -x

source $GRNENV_HOME/libexec/grnenv-config

cat <<USAGE
Usage: grnenv COMMAND [OPTIONS]
Commands:
  build
  export
  global
  groonga-version
  help
  local
  plugin-install
  plugin-uninstall
  rehash
  root
  version
  versions
USAGE
