#!/usr/bin/env bash
set -e
[ -n "$GRNENV_DEBUG" ] && set -x

version=$1

if [ "$version" = "" ]; then
  echo "Usage: grnenv build VERSION"
  exit 1
fi

tmp_dir=/tmp/grnenv-$version
mkdir -p $tmp_dir
cd $tmp_dir

wget http://packages.groonga.org/source/groonga/groonga-$version.tar.gz
tar xzvf groonga-$version.tar.gz
cd groonga-$version

mkdir -p $GRNENV_HOME/versions/$version
./configure --prefix=$GRNENV_HOME/versions/$version
make
make install
