#!/usr/bin/env bash
set -e
[ -n "$GRNENV_DEBUG" ] && set -x

source $GRNENV_HOME/libexec/grnenv-config

if [ -f ".groonga-version" ]; then
  version=$(cat .groonga-version)
else
  version=$(cat $GRNENV_HOME/version)
fi

echo $version
