#!/usr/bin/env bash
set -e
[ -n "$GRNENV_DEBUG" ] && set -x

version=$1

if [ "$version" = "" ]; then
  echo "Usage: grnenv global VERSION"
  exit 1
fi

if [ ! -d "$GRNENV_HOME/versions/$version" ]; then
  echo "grnenv: not installed: <$version>"
  exit 1
fi

echo $version > $GRNENV_HOME/version

grnenv-rehash
