#!/usr/bin/env bash
set -e
[ -n "$GRNENV_DEBUG" ] && set -x

source $GRNENV_HOME/libexec/grnenv-config

version=$1

if [ "$version" = "" ]; then
  abort "Usage: grnenv build VERSION"
fi

tmp_dir=/tmp/grnenv-$version
rm -fr $tmp_dir
mkdir -p $tmp_dir
cd $tmp_dir

wget http://packages.groonga.org/source/groonga/groonga-$version.tar.gz
tar xzvf groonga-$version.tar.gz
cd groonga-$version

./configure --prefix=$GRNENV_HOME/versions/$version
make
make install
