#!/usr/bin/env bash
set -e
[ -n "$GRNENV_DEBUG" ] && set -x

source $GRNENV_HOME/libexec/grnenv-config

version=$1

if [ "$version" = "" ]; then
  abort "Usage: grnenv global VERSION"
fi

if [ ! -d "$GRNENV_HOME/versions/$version" ]; then
  if [ "$version" != "system" ]; then
    abort "grnenv: not installed: <$version>"
  fi
fi

echo $version > $GRNENV_HOME/version

grnenv-rehash
