#!/usr/bin/env bash
set -e
[ -n "$GRNENV_DEBUG" ] && set -x

source $GRNENV_HOME/libexec/grnenv-config

version=$1

if [ "$version" = "" ]; then
  abort "Usage: grnenv local VERSION"
fi

if [ ! -d "$GRNENV_HOME/versions/$version" ]; then
  abort "grnenv: not installed: <$version>"
fi

echo $version > .groonga-version

grnenv-rehash
