#!/usr/bin/env bash
set -e
[ -n "$GRNENV_DEBUG" ] && set -x

version=$1

if [ "$version" = "" ]; then
  echo "Usage: grnenv local VERSION"
  exit 1
fi

echo $version > .groonga-version

grnenv-rehash
