#!/usr/bin/env bash
set -e
[ -n "$GRNENV_DEBUG" ] && set -x

source $GRNENV_HOME/libexec/grnenv-config

shims_dir=$GRNENV_HOME/shims
version=$(grnenv-groonga-version)
bin_dir=$GRNENV_HOME/versions/$version/bin

clear_shims() {
  rm -f $shims_dir/*
}

create_shim() {
  local shim_path=$shims_dir/$1
  cat > "$shim_path" <<'SHIM'
#!/usr/bin/env bash
set -e
[ -n "$GRNENV_DEBUG" ] && set -x

libexec_dir=$GRNENV_HOME/libexec
export PATH="$libexec_dir:$PATH"

version=$(grnenv-groonga-version)

program=$(basename $0)
if [ "$version" = "system" ]; then
  (
    PATH=$(eval "echo $PATH" | sed -e "s/$GRNENV_HOME/shims:*//g")
    $program $@
  )
else
  exec $GRNENV_HOME/versions/$version/bin/$program $@
fi
SHIM
  chmod +x "$shim_path"
}

clear_shims

if [ "$version" = "system" ]; then
  files=""
else
  files=$(ls $bin_dir/*)
fi

for file in $files
do
  bin_name=$(basename $file)
  create_shim $bin_name
done
