#!/usr/bin/env bash
set -e
[ -n "$GRNENV_DEBUG" ] && set -x

source $GRNENV_HOME/libexec/grnenv-config

if [ -f ".groonga-version" ]; then
  version=$(cat .groonga-version)
else
  if [ -f $GRNENV_HOME/version ]; then
  version=$(cat $GRNENV_HOME/version)
  else
    version="system"
  fi
fi

echo $version
